### ISSUE TITLE
iOS doesn't play audio

### ISSUE THREAD

**Issue by prplz** [prplz/baker.cat#1]
Need to use a touch event to make audio play on iOS which I think isn't very cool by apple but whatever we have to deal with it anyway this is our job right?

**Comment by lolitsalex** [comment]
Possible fix?
myAudio = new Audio('wtfamidoingwithmylife.mp3');
myAudio.addEventListener('ended', function() {
    this.currentTime = 0;
    this.play();
}, false);
myAudio.play();

Sorry on my phone so this,is just some code from memory

**Comment by prplz** [comment]
I don't think you understand the issue

**Comment by lolitsalex** [comment]
Yea I don't think I did it was 3 am when I said that, nvm I can delete it mb

**Comment by AlfieC** [comment]
mac osx doesnt play audio either

**Comment by prplz** [comment]
Ok thanks alfie :(

**Comment by meteficha** [comment]
It seems that #9 did not fix iOS unfortunately.

**Comment by prplz** [comment]
Correct, iOS has a weird system where you must have the user press something to enable audio.
